# データ解析のための統計モデリング入門
## 7章 一般化線形混合モデル
### 7.2 過分散と個体差

In [1]:
d <- read.csv("../prepared/chapter7/data.csv")
d

    N y x id
1   8 0 2  1
2   8 1 2  2
3   8 2 2  3
4   8 4 2  4
5   8 1 2  5
6   8 0 2  6
7   8 0 2  7
8   8 7 2  8
9   8 1 2  9
10  8 6 2 10
11  8 0 2 11
12  8 0 2 12
13  8 0 2 13
14  8 0 2 14
15  8 0 2 15
16  8 1 2 16
17  8 3 2 17
18  8 5 2 18
19  8 3 2 19
20  8 7 2 20
21  8 2 3 21
22  8 1 3 22
23  8 0 3 23
24  8 6 3 24
25  8 1 3 25
26  8 2 3 26
27  8 0 3 27
28  8 0 3 28
29  8 0 3 29
30  8 3 3 30
⋮   ⋮ ⋮ ⋮ ⋮
71  8 8 5  71
72  8 8 5  72
73  8 8 5  73
74  8 6 5  74
75  8 7 5  75
76  8 4 5  76
77  8 5 5  77
78  8 1 5  78
79  8 8 5  79
80  8 2 5  80
81  8 1 6  81
82  8 1 6  82
83  8 0 6  83
84  8 8 6  84
85  8 8 6  85
86  8 8 6  86
87  8 8 6  87
88  8 8 6  88
89  8 8 6  89
90  8 8 6  90
91  8 8 6  91
92  8 0 6  92
93  8 6 6  93
94  8 3 6  94
95  8 3 6  95
96  8 7 6  96
97  8 5 6  97
98  8 7 6  98
99  8 2 6  99
100 8 8 6 100

In [3]:
d4 <- d[d$x == 4,]
d4

   N y x id
41 8 6 4 41
42 8 2 4 42
43 8 0 4 43
44 8 5 4 44
45 8 6 4 45
46 8 2 4 46
47 8 8 4 47
48 8 2 4 48
49 8 7 4 49
50 8 7 4 50
51 8 8 4 51
52 8 0 4 52
53 8 4 4 53
54 8 7 4 54
55 8 3 4 55
56 8 1 4 56
57 8 3 4 57
58 8 2 4 58
59 8 8 4 59
60 8 0 4 60

In [4]:
table(d4$y)

0 1 2 3 4 5 6 7 8
3 1 4 2 1 1 2 3 3

In [5]:
c(mean(d4$y), var(d4$y))

[1] 4.050000 8.365789

### 7.4 一般化線形混合モデルの最尤推定

In [6]:
install.packages('glmmML')

Updating HTML index of packages in '.Library'
Making 'packages.html' ... done

In [7]:
library('glmmML')

In [8]:
glmmML(cbind(y, N - y) ~ x, data = d, family = binomial, cluster = id)

Call:  glmmML(formula = cbind(y, N - y) ~ x, family = binomial, data = d,      cluster = id)


              coef se(coef)      z Pr(>|z|)
(Intercept) -4.190   0.8777 -4.774 1.81e-06
x            1.005   0.2075  4.843 1.28e-06

Scale parameter in mixing distribution:  2.408 gaussian
Std. Error:                              0.2202

        LR p-value for H_0: sigma = 0:  2.136e-55

Residual deviance: 269.4 on 97 degrees of freedom 	AIC: 275.4